src/Entity/Account.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="accounts")
 * @ORM\Entity(repositoryClass="App\Repository\AccountRepository")
 */
class Account
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_main;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Plan", inversedBy="accounts")
     * @ORM\JoinColumn(nullable=true)
     */
    private $plan;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_register;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompanyAccounts", mappedBy="account")
     */
    private $companyAccounts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Request", mappedBy="account")
     */
    private $requests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="provider")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="account")
     */
    private $notes;

    public function __construct()
    {
        $this->companyAccounts = new ArrayCollection();
        $this->requests = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsMain(): ?bool
    {
        return $this->is_main;
    }

    public function setIsMain(bool $is_main): self
    {
        $this->is_main = $is_main;

        return $this;
    }

    public function getPlan(): ?Plan
    {
        return $this->plan;
    }

    public function setPlan(?Plan $plan): self
    {
        $this->plan = $plan;

        return $this;
    }

    public function getDateRegister(): ?\DateTimeInterface
    {
        return $this->date_register;
    }

    public function setDateRegister(\DateTimeInterface $date_register): self
    {
        $this->date_register = $date_register;

        return $this;
    }

    /**
     * @return Collection|CompanyAccounts[]
     */
    public function getCompanyAccounts(): Collection
    {
        return $this->companyAccounts;
    }

    public function addCompanyAccount(CompanyAccounts $companyAccount): self
    {
        if (!$this->companyAccounts->contains($companyAccount)) {
            $this->companyAccounts[] = $companyAccount;
            $companyAccount->setAccount($this);
        }

        return $this;
    }

    public function removeCompanyAccount(CompanyAccounts $companyAccount): self
    {
        if ($this->companyAccounts->contains($companyAccount)) {
            $this->companyAccounts->removeElement($companyAccount);
            // set the owning side to null (unless already changed)
            if ($companyAccount->getAccount() === $this) {
                $companyAccount->setAccount(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Request[]
     */
    public function getRequests(): Collection
    {
        return $this->requests;
    }

    public function addRequest(Request $request): self
    {
        if (!$this->requests->contains($request)) {
            $this->requests[] = $request;
            $request->setAccount($this);
        }

        return $this;
    }

    public function removeRequest(Request $request): self
    {
        if ($this->requests->contains($request)) {
            $this->requests->removeElement($request);
            // set the owning side to null (unless already changed)
            if ($request->getAccount() === $this) {
                $request->setAccount(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setProvider($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getProvider() === $this) {
                $event->setProvider(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setAccount($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getAccount() === $this) {
                $note->setAccount(null);
            }
        }

        return $this;
    }
}

src/Entity/CompanyAccounts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompanyAccountsRepository")
 */
class CompanyAccounts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Account", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $main_access;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $possition;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $working_time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $event_access;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getStaffAccess(): ?bool
    {
        return $this->staff_access;
    }

    public function setStaffAccess(bool $staff_access): self
    {
        $this->staff_access = $staff_access;

        return $this;
    }

    public function getStaffManage(): ?bool
    {
        return $this->staff_manage;
    }

    public function setStaffManage(bool $staff_manage): self
    {
        $this->staff_manage = $staff_manage;

        return $this;
    }

    public function getServiceAccess(): ?bool
    {
        return $this->service_access;
    }

    public function setServiceAccess(bool $service_access): self
    {
        $this->service_access = $service_access;

        return $this;
    }

    public function getServiceManage(): ?bool
    {
        return $this->service_manage;
    }

    public function setServiceManage(bool $service_manage): self
    {
        $this->service_manage = $service_manage;

        return $this;
    }

    public function getClientAccess(): ?bool
    {
        return $this->client_access;
    }

    public function setClientAccess(bool $client_access): self
    {
        $this->client_access = $client_access;

        return $this;
    }

    public function getClientManage(): ?bool
    {
        return $this->client_manage;
    }

    public function setClientManage(bool $client_manage): self
    {
        $this->client_manage = $client_manage;

        return $this;
    }

    public function getMainAccess(): ?bool
    {
        return $this->main_access;
    }

    public function setMainAccess(bool $main_access): self
    {
        $this->main_access = $main_access;

        return $this;
    }

    public function getPossition(): ?string
    {
        return $this->possition;
    }

    public function setPossition(?string $possition): self
    {
        $this->possition = $possition;

        return $this;
    }

    public function getWorkingTime(): ?string
    {
        return $this->working_time;
    }


    public function setWorkingTime(?string $working_time): self
    {
        $this->working_time = $working_time;

        return $this;
    }


    public function getEventAccess()
    {
        return $this->event_access;
    }


    public function setEventAccess($event_access): void
    {
        $this->event_access = $event_access;
    }
}

templates/staff/add_staff.html.twig
{% extends '/layout/layout.html.twig' %}

{% block custom_css_resource %}
    <link href="{{ settings.static_url }}/bootstrap/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="{{ settings.static_url }}/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet"/>
{% endblock %}


{% block body %}
    <div class="row">
        {% include 'partials/more/flash_messages.html.twig' %}
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <!---edit profile form -->
                {% include 'staff/forms/add_staff.html.twig' %}
                <!---/end profile form -->
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_resources %}
    <script src="{{ settings.static_url }}/bootstrap/js/bootstrap-toggle.min.js"></script>
    <script src="{{ settings.static_url }}/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>
    <script src="{{ settings.static_url }}/dist/js/pages/add_staff.js"></script>
{% endblock %}

templates/staff/edit_staff.html.twig
{% extends '/layout/layout.html.twig' %}
{% block custom_css_resource %}
    <link href="{{ settings.static_url }}/bootstrap/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="{{ settings.static_url }}/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet"/>
{% endblock %}
{% block body %}
    <div class="row">
        {% include 'partials/more/flash_messages.html.twig' %}
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <!---edit profile form -->
                {% include 'staff/forms/add_staff.html.twig' %}
                <!---/end profile form -->
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_resources %}

    <script src="{{ settings.static_url }}/plugins/fullcalendar/lib/moment.min.js" type="text/javascript"></script>
    <script src="{{ settings.static_url }}/bootstrap/js/bootstrap-toggle.min.js"></script>
    <script src="{{ settings.static_url }}/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>
    <script src="{{ settings.static_url }}/dist/js/pages/add_staff.js"></script>
{% endblock %}

templates/staff/staff.html.twig
{% extends "/layout/layout.html.twig" %}
{% block body %}
    <div class="row">
        {% include 'partials/more/flash_messages.html.twig' %}
        <div class="col-md-12">
            <!-- TABLE: LATEST ORDERS -->
            <div class="box box-info">
                <div class="box-header with-border">
                    {% include "partials/more/table_search_box.html.twig" %}
                    <div class="box-tools pull-right">
                        {% if info.staffManage %}
                            <a href="{{ path('add_staff', {'slug': company.slug}) }}" class="btn btn-block btn-primary btn-sm">
                                Добави служител
                            </a>
                        {% endif %}
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table no-margin">
                            <thead>
                            <tr>
                                <th width="80%">Име</th>
                                <th width="13%">Опции</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for staff in staffs %}
                                    <tr>
                                        <td>{{ staff.account.name }}</td>
                                        <td>
                                            <a href="{{ path('send_message', {'id': 'false', 'receiver_id': staff.account.id}) }}" class="btn btn-xs {% if account.id == staff.account.id %}disabled{% endif %}" data-toggle="tooltip" data-placement="top" title="Изпрати лично съобщение"><i class="fa fa-comment"></i></a>

                                            {% if info.staffManage == 1 and (not staff.mainAccess or not staff.account.isMain) or (account.isMain and staff.account.id==account.id) %}
                                                {% if account.isMain and info.MainAccess %}
                                                 <a class="btn btn-xs" href="{{ path('edit_staff', {'slug': slug, 'id': staff.account.id}) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                 {% endif %}


                                                <button class="btn btn-xs confirm_delete" data-url="{{ path('remove_staff', {'slug': slug, 'id': staff.account.id}) }}"><i class="fa fa-remove" aria-hidden="true"></i></button>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        {{ knp_pagination_render(staffs) }}
                    </ul>
                </div><!-- /.box-footer -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
{% endblock %}