src/Entity/CompanyAccounts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompanyAccountsRepository")
 */
class CompanyAccounts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Account", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $main_access;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $possition;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $working_time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $event_access;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getStaffAccess(): ?bool
    {
        return $this->staff_access;
    }

    public function setStaffAccess(bool $staff_access): self
    {
        $this->staff_access = $staff_access;

        return $this;
    }

    public function getStaffManage(): ?bool
    {
        return $this->staff_manage;
    }

    public function setStaffManage(bool $staff_manage): self
    {
        $this->staff_manage = $staff_manage;

        return $this;
    }

    public function getServiceAccess(): ?bool
    {
        return $this->service_access;
    }

    public function setServiceAccess(bool $service_access): self
    {
        $this->service_access = $service_access;

        return $this;
    }

    public function getServiceManage(): ?bool
    {
        return $this->service_manage;
    }

    public function setServiceManage(bool $service_manage): self
    {
        $this->service_manage = $service_manage;

        return $this;
    }

    public function getClientAccess(): ?bool
    {
        return $this->client_access;
    }

    public function setClientAccess(bool $client_access): self
    {
        $this->client_access = $client_access;

        return $this;
    }

    public function getClientManage(): ?bool
    {
        return $this->client_manage;
    }

    public function setClientManage(bool $client_manage): self
    {
        $this->client_manage = $client_manage;

        return $this;
    }

    public function getMainAccess(): ?bool
    {
        return $this->main_access;
    }

    public function setMainAccess(bool $main_access): self
    {
        $this->main_access = $main_access;

        return $this;
    }

    public function getPossition(): ?string
    {
        return $this->possition;
    }

    public function setPossition(?string $possition): self
    {
        $this->possition = $possition;

        return $this;
    }

    public function getWorkingTime(): ?string
    {
        return $this->working_time;
    }


    public function setWorkingTime(?string $working_time): self
    {
        $this->working_time = $working_time;

        return $this;
    }


    public function getEventAccess()
    {
        return $this->event_access;
    }


    public function setEventAccess($event_access): void
    {
        $this->event_access = $event_access;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="services")
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $cost;

    /**
     * @ORM\Column(type="integer")
     */
    private $time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_private;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="services")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ServiceProviders", mappedBy="service")
     */
    private $serviceProviders;

    public function __construct()
    {
        $this->serviceProviders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCost(): ?float
    {
        return $this->cost;
    }

    public function setCost(float $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(int $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getIsPrivate(): ?bool
    {
        return $this->is_private;
    }

    public function setIsPrivate(bool $is_private): self
    {
        $this->is_private = $is_private;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|ServiceProviders[]
     */
    public function getServiceProviders(): Collection
    {
        return $this->serviceProviders;
    }

    public function addServiceProvider(ServiceProviders $serviceProvider): self
    {
        if (!$this->serviceProviders->contains($serviceProvider)) {
            $this->serviceProviders[] = $serviceProvider;
            $serviceProvider->setService($this);
        }

        return $this;
    }

    public function removeServiceProvider(ServiceProviders $serviceProvider): self
    {
        if ($this->serviceProviders->contains($serviceProvider)) {
            $this->serviceProviders->removeElement($serviceProvider);
            // set the owning side to null (unless already changed)
            if ($serviceProvider->getService() === $this) {
                $serviceProvider->setService(null);
            }
        }

        return $this;
    }
}

src/Controller/ServicesController.php
<?php
/**
 * Created by PhpStorm.
 * User: krasimir
 * Date: 19.12.18
 * Time: 13:46
 */

namespace App\Controller;
use App\Entity\AccountsCompanies;
use App\Entity\CompanyServices;
use App\Entity\Service;
use App\Entity\ServiceProviders;
use App\Entity\Services;
use App\Entity\ServicesProviders;
use App\Forms\AddService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class ServicesController extends GlobalController
{
    /**
     * @Route("/company/{slug}/services", name="company_services", methods={"GET"})
     */

    public function company_services($slug){
        if(!$this->account){
            return $this->redirectToRoute("account_login");
        }

        $info = $this->company_service->companyAccess($slug, 'getServiceAccess');

        $company = $info->getCompany();

        $search_word = $this->request->get("search");

        $services = $this->getDoctrine()->getRepository(Service::class)->getServices($search_word, $company);
        $services = $this->service->pages($services, 10);

        $path = $company->getName().", Услуги";
        $paths = $this->service->paths("Табло, Компания, ".$path);
        $menu = ['view' => 'companies', 'active' => 'company_services'];

        return $this->render("services/services.html.twig", [
            'paths' => $paths,
            'menu' => $menu,
            'slug' => $company->getSlug(),
            'services' => $services,
            'info' => $info
        ]);
    }

    /**
     * @Route("/company/{slug}/services/add/{id}", defaults={"id" = null}, name="company_add_service", methods={"GET", "POST"})
     */
    public function add_service($slug, $id, Request $request){
        if(!$this->account){
            return $this->redirectToRoute("account_login");
        }

        $info = $this->company_service->companyAccess($slug, 'getServiceManage', 'company_services', ['slug' => $slug]);

        $service = $id ? $this->getDoctrine()->getRepository("App:Service")->findOneBy(['id' =>$id]) : new Service();

        $company = $info->getCompany();


        $form = $this->createForm(AddService::class, $service);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            if(!$id){
                $service->setCompany($company);
            }

            $this->service->saveData($service);
            $this->addFlash("success", $id ? 'Успешно обновихте услугата':'Успешно добавихте услугата');
            return $this->redirectToRoute("company_services", ['slug' => $slug]);
        }


        $path = $company->getName().", Услуги, Добавяне на услуга";
        $paths = $this->service->paths("Табло, Компания, ".$path);
        $menu = ['view' => 'companies', 'active' => 'company_services'];

        return $this->render("services/service_add.html.twig", [
            'paths' => $paths,
            'menu' => $menu,
            'slug' => $company->getSlug(),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("company/{slug}/services/remove/{service_id}", name="remove_service", methods={"POST", "GET"})
     */
    public function remove_service($slug, $service_id){
        if(!$this->account){
            return $this->redirectToRoute("account_login");
        }

        $info = $this->company_service->companyAccess($slug, 'getServiceManage', 'company_services', ['slug' => $slug]);

        $service = $this->getDoctrine()->getRepository(Service::class)->findOneBy(['id' => $service_id, 'company' => $info->getCompany()]);

        if(!$service){
            $this->addFlash('danger', 'Упссс! Опитвате се изтриете услуга, която не съществува');
            return $this->redirectToRoute("company_services", ['slug' => $slug]);
        }

        #delete events
        $this->getDoctrine()->getRepository("App:Event")->deleteEvents(false, false, false, $service);

        #delete providers
        $this->getDoctrine()->getRepository("App:ServiceProviders")->deleteProviders($service);

        #delete service
        $this->service->deleteData($service); //delete service from company

        return $this->redirectToRoute("company_services", ['slug' => $slug]);
    }

    /**
     * @Route("company/{slug}/services/{id}/providers", name="service_providers", methods={"GET"})
     */
    public function service_providers($slug, $id){
        if(!$this->account){
            $this->redirectToRoute("account_login");
        }

        $info = $this->company_service->companyAccess($slug, 'getServiceAccess');

        $service = $this->getDoctrine()->getRepository(Service::class)->findOneBy(['id' => $id, 'company' => $info->getCompany()]);


        #check company exists
        if(!$service) {
            $this->addFlash('danger', 'Упссссс! Грешка! Нещо се обърка, моля опитайте отново!');
            return $this->redirectToRoute("index_companies");
        }

        $company = $info->getCompany();


        $search_word = $this->request->get("search");
        $providers = $this->getDoctrine()->getRepository(ServiceProviders::class)->getProviders($service, $search_word);
        $providers = $this->service->pages($providers, 10);


        $path = $company->getName().", Услуги, ".$service->getName().", Служители";
        $paths = $this->service->paths("Табло, Компания, ".$path);

        $menu = ['view' => "companies", 'active' => 'company_services'];

        $add_providers = $this->getDoctrine()->getRepository(ServiceProviders::class)->getAccountForAddtoServicers($company, $providers);


        return $this->render("services/service_providers.html.twig", [
            'info' => $info,
            'slug' => $slug,
            'paths' => $paths,
            'providers' => $providers,
            'add_providers' => $add_providers,
            'service' => $service,
            'company' => $company,
            'menu' => $menu
        ]);
    }

    /**
     * @Route("company/{slug}/services/{service_id}/providers/remove/{provider_id}", name="remove_provider", methods={"POST", "GET"})
     */
    public function remove_provider($slug, $service_id, $provider_id){
        if(!$this->account){
            return $this->redirectToRoute("account_login");
        }

        $info = $this->company_service->companyAccess($slug, 'getServiceManage', 'service_providers', ['slug' => $slug, 'id' => $service_id]);

        $service = $this->getDoctrine()->getRepository(Service::class)->findOneBy(['id' => $service_id, 'company' => $info->getCompany()]);

        if(!$service){
            $this->addFlash('danger', 'Упссс! Услугата не съществува!');
            return $this->redirectToRoute("company_services", ['slug' => $slug]);
        }

        $provider = $this->getDoctrine()->getRepository(ServiceProviders::class)->findOneBy(['service' => $service, 'id' => $provider_id]);

        if(!$provider){
             $this->addFlash('danger', 'Упссс! Опитвате се изтриете провайдър, която не съществува');
             return $this->redirectToRoute("service_providers", ['slug' => $slug, 'id' => $service->getId()]);
        }

        $this->service->deleteData($provider);
        $this->addFlash('success', 'Провайдърът е изтрит успешно');
        return $this->redirectToRoute("service_providers", ['slug' => $slug, 'id' => $service->getId()]);
    }

}

templates/services/service_add.html.twig
{% extends '/layout/layout.html.twig' %}

{% block body %}
<div class="row">
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <!---edit profile form -->
            {% include 'services/forms/service_add_form.html.twig' %}
            <!---/end profile form -->

        </div>
    </div>
</div>
{% endblock %}

templates/services/service_providers.html.twig
{% extends '/layout/layout.html.twig' %}

{% block body %}
    <div class="row">
        <!-- flash messages -->
        {% include 'partials/more/flash_messages.html.twig' %}
        <!-- /end flash messages -->
        <div class="col-md-12">
            <!-- TABLE: LATEST ORDERS -->
            <div class="box box-info">
                <div class="box-header with-border">
                    {% include "partials/more/table_search_box.html.twig" %}
                    <div class="box-tools pull-right">
                        {% if info.serviceManage  %}
                            <a href="javascript:;" class="btn btn-block btn-primary btn-sm" data-toggle="modal" data-target="#addProviders" data-placement="top">
                                Добави
                            </a>
                        {% endif %}
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        {% if providers is empty %}
                            <div class="callout callout-danger">
                                <h4>Упссс, няма добавени служители, които могат да извършват тази услуга!</h4>

                                <p>Съжаляваме, но изглежда все още няма добавени служители, които могат да извършват тази услуга.
                                </p>
                            </div>
                        {% else %}
                            <table class="table no-margin">
                                <thead>
                                <tr>
                                    <th width="90%">Име</th>
                                    {% if info.serviceManage %}
                                        <th>Изтрий</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody class="elements">
                                {% for provider in providers %}
                                    <tr data-id="{{ provider.id }}">
                                        <td>{{ provider.account.name }}</td>
                                        {% if info.serviceManage %}
                                            <td>
                                                <button class="btn btn-xs confirm_delete" data-url="{{ path('remove_provider', {'slug': slug, 'service_id': service.id, 'provider_id': provider.id}) }}"><i class="fa fa-remove" aria-hidden="true"></i></button>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        {% endif %}
                    </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                    <ul class="pagination pagination-sm no-margin pull-right">
                        {{ knp_pagination_render(providers) }}
                    </ul>
                </div><!-- /.box-footer -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
    {% include "/services/modals/add_providers.html.twig" %}
    {% include "partials/modals/confirm_delete.html.twig" %}
{% endblock %}

templates/services/services.html.twig
{% extends '/layout/layout.html.twig' %}

{% block body %}
        <div class="row">
            <!-- flash messages -->
            {% include 'partials/more/flash_messages.html.twig' %}
            <!-- /end flash messages -->
            <div class="col-md-12">
                <!-- TABLE: LATEST ORDERS -->
                <div class="box box-info">
                    <div class="box-header with-border">
                        {% include "partials/more/table_search_box.html.twig" %}
                        <div class="box-tools pull-right">
                            {% if info.serviceManage  %}
                            <a href="{{ path('company_add_service', {'slug': slug}) }}" class="btn btn-block btn-primary btn-sm">
                                Добави услуга
                            </a>
                            {% endif %}
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            {% if services is empty %}
                                <div class="callout callout-danger">
                                    <h4>Упссс, няма добавени услуги!</h4>

                                    <p>Съжаляваме, но изглежда все още няма добавени услуги към тази компания.
                                        <br />
                                    </p>
                                </div>
                            {% else %}
                            <table class="table no-margin">
                                <thead>
                                <tr>
                                    <th>Услуга</th>
                                    <th>Цена</th>
                                    <th>Времетраене</th>
                                    {% if info.serviceManage %}
                                    <th width="15%">Управление</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for service in services %}
                                    <tr>
                                        <td>{{ service.name }}</td>
                                        <td>{{ service.cost }}лв</td>
                                        <td>{{ service.time }}мин.</td>
                                        {% if info.serviceManage %}
                                        <td>
                                            <a href="{{ path('service_providers', {'slug': slug, 'id': service.id}) }}" class="btn btn-xs" data-toggle="tooltip" data-placement="top" title="Служители"><i class="fa fa-user"></i></a>


                                            <a href="{{ path('company_add_service', {'slug': slug, 'id': service.id}) }}" class="btn btn-xs" data-toggle="tooltip" data-placement="top" title="Редактирай"><i class="fa fa-pencil"></i></a>

                                            <button class="btn btn-xs confirm_delete" data-url="{{ path("remove_service", {'slug': slug, 'service_id': service.id}) }}"><i class="fa fa-remove" aria-hidden="true"></i></button>

                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            {% endif %}
                        </div><!-- /.table-responsive -->
                    </div><!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            {{ knp_pagination_render(services) }}
                        </ul>
                    </div><!-- /.box-footer -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
{% endblock %}