src/Entity/Account.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="accounts")
 * @ORM\Entity(repositoryClass="App\Repository\AccountRepository")
 */
class Account
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_main;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Plan", inversedBy="accounts")
     * @ORM\JoinColumn(nullable=true)
     */
    private $plan;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_register;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompanyAccounts", mappedBy="account")
     */
    private $companyAccounts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Request", mappedBy="account")
     */
    private $requests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="provider")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="account")
     */
    private $notes;

    public function __construct()
    {
        $this->companyAccounts = new ArrayCollection();
        $this->requests = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsMain(): ?bool
    {
        return $this->is_main;
    }

    public function setIsMain(bool $is_main): self
    {
        $this->is_main = $is_main;

        return $this;
    }

    public function getPlan(): ?Plan
    {
        return $this->plan;
    }

    public function setPlan(?Plan $plan): self
    {
        $this->plan = $plan;

        return $this;
    }

    public function getDateRegister(): ?\DateTimeInterface
    {
        return $this->date_register;
    }

    public function setDateRegister(\DateTimeInterface $date_register): self
    {
        $this->date_register = $date_register;

        return $this;
    }

    /**
     * @return Collection|CompanyAccounts[]
     */
    public function getCompanyAccounts(): Collection
    {
        return $this->companyAccounts;
    }

    public function addCompanyAccount(CompanyAccounts $companyAccount): self
    {
        if (!$this->companyAccounts->contains($companyAccount)) {
            $this->companyAccounts[] = $companyAccount;
            $companyAccount->setAccount($this);
        }

        return $this;
    }

    public function removeCompanyAccount(CompanyAccounts $companyAccount): self
    {
        if ($this->companyAccounts->contains($companyAccount)) {
            $this->companyAccounts->removeElement($companyAccount);
            // set the owning side to null (unless already changed)
            if ($companyAccount->getAccount() === $this) {
                $companyAccount->setAccount(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Request[]
     */
    public function getRequests(): Collection
    {
        return $this->requests;
    }

    public function addRequest(Request $request): self
    {
        if (!$this->requests->contains($request)) {
            $this->requests[] = $request;
            $request->setAccount($this);
        }

        return $this;
    }

    public function removeRequest(Request $request): self
    {
        if ($this->requests->contains($request)) {
            $this->requests->removeElement($request);
            // set the owning side to null (unless already changed)
            if ($request->getAccount() === $this) {
                $request->setAccount(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setProvider($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getProvider() === $this) {
                $event->setProvider(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setAccount($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getAccount() === $this) {
                $note->setAccount(null);
            }
        }

        return $this;
    }
}

src/Entity/CompanyAccounts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompanyAccountsRepository")
 */
class CompanyAccounts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Account", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="companyAccounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $staff_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $service_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_access;

    /**
     * @ORM\Column(type="boolean")
     */
    private $client_manage;

    /**
     * @ORM\Column(type="boolean")
     */
    private $main_access;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $possition;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $working_time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $event_access;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getStaffAccess(): ?bool
    {
        return $this->staff_access;
    }

    public function setStaffAccess(bool $staff_access): self
    {
        $this->staff_access = $staff_access;

        return $this;
    }

    public function getStaffManage(): ?bool
    {
        return $this->staff_manage;
    }

    public function setStaffManage(bool $staff_manage): self
    {
        $this->staff_manage = $staff_manage;

        return $this;
    }

    public function getServiceAccess(): ?bool
    {
        return $this->service_access;
    }

    public function setServiceAccess(bool $service_access): self
    {
        $this->service_access = $service_access;

        return $this;
    }

    public function getServiceManage(): ?bool
    {
        return $this->service_manage;
    }

    public function setServiceManage(bool $service_manage): self
    {
        $this->service_manage = $service_manage;

        return $this;
    }

    public function getClientAccess(): ?bool
    {
        return $this->client_access;
    }

    public function setClientAccess(bool $client_access): self
    {
        $this->client_access = $client_access;

        return $this;
    }

    public function getClientManage(): ?bool
    {
        return $this->client_manage;
    }

    public function setClientManage(bool $client_manage): self
    {
        $this->client_manage = $client_manage;

        return $this;
    }

    public function getMainAccess(): ?bool
    {
        return $this->main_access;
    }

    public function setMainAccess(bool $main_access): self
    {
        $this->main_access = $main_access;

        return $this;
    }

    public function getPossition(): ?string
    {
        return $this->possition;
    }

    public function setPossition(?string $possition): self
    {
        $this->possition = $possition;

        return $this;
    }

    public function getWorkingTime(): ?string
    {
        return $this->working_time;
    }


    public function setWorkingTime(?string $working_time): self
    {
        $this->working_time = $working_time;

        return $this;
    }


    public function getEventAccess()
    {
        return $this->event_access;
    }


    public function setEventAccess($event_access): void
    {
        $this->event_access = $event_access;
    }
}

src/Entity/Plan.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="plans")
 * @ORM\Entity(repositoryClass="App\Repository\PlanRepository")
 */
class Plan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $companies_limit;

    /**
     * @ORM\Column(type="integer")
     */
    private $staffs_limit;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Account", mappedBy="plan")
     */
    private $accounts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCompaniesLimit(): ?int
    {
        return $this->companies_limit;
    }

    public function setCompaniesLimit(int $companies_limit): self
    {
        $this->companies_limit = $companies_limit;

        return $this;
    }

    public function getStaffsLimit(): ?int
    {
        return $this->staffs_limit;
    }

    public function setStaffsLimit(int $staffs_limit): self
    {
        $this->staffs_limit = $staffs_limit;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts[] = $account;
            $account->setPlan($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        if ($this->accounts->contains($account)) {
            $this->accounts->removeElement($account);
            // set the owning side to null (unless already changed)
            if ($account->getPlan() === $this) {
                $account->setPlan(null);
            }
        }

        return $this;
    }
}

templates/companies/partials/companies-table.html.twig
<div class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Моите компании</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        {% if companies %}
        <table class="table no-margin">
            <tbody class="elements">
            {% for company in companies %}
                <tr data-id="{{ company.company.id }}">
                    <td>{{ company.company.name }}</td>
                    <td class="text-right">
                        <a href="{{ path('company_view', {'slug': company.company.slug}) }}" class="btn btn-xs"><i class="fa fa-dashboard"></i></a>
                        {% if account.isMain %}
                        <a href="{{ path('edit_company', {'slug': company.company.slug}) }}" class="btn btn-xs"><i class="fa fa-pencil"></i></a>
                        <button class="btn btn-xs confirm_delete" data-url="{{ path('remove_company', {'slug': company.company.slug}) }}"><i class="fa fa-remove" aria-hidden="true"></i></button>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-info"></i> Няма компании!</h4>
                Съжаляваме, но вашият профил не е асоциран с нито една компания! Ако Вие сте с администраторски профил, може да добавите компания от формата в дясно.
            </div>
        {% endif %}
    </div><!-- /.box-body -->
</div><!-- /.box -->

{% include "partials/modals/confirm_delete.html.twig" %}

templates/companies/partials/create_company_panel.html.twig
<div class="col-md-{% if edit is defined and edit %}12{% else %}6{% endif %}">
    <!-- PRODUCT LIST -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{% if edit is defined and edit %}Редактиране на компания{% else %}Добави компания{% endif %}</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">
            {% if not account.isMain or (account.plan.companiesLimit < companies|length or account.plan.companiesLimit == companies|length) and (edit is not defined) %}
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Грешка</h4>
                    Максималният брой компании е достигнат и не може да добавяте нови!
                </div>
            {% else %}
                {% include "companies/forms/create_company_form.html.twig" %}
            {% endif %}
        </div>
        <div class="box-footer text-center">

        </div>
    </div>
</div>

templates/companies/partials/events.html.twig
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header" style="cursor: move;">
                <i class="ion ion-clipboard"></i>
                <h3 class="box-title">Вашите задачи за днес</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <ul class="todo-list">
                    {% if not my_events %}
                        <div class="callout callout-warning">
                            <h4>Нямате задачи за днес!</h4>
                        </div>
                    {% endif %}

                    {% for event in my_events %}
                        <li class="item" data-id="{{ event.id }}">
                            <span class="text">{{ event.service.name }}<small>(клиент: {{ event.client.name }})</small></span>
                            <small class="label label-default"><i class="fa fa-clock-o"></i> {{ event.start|date("H:i") }} - {{ event.end|date("H:i") }}</small>
                            {% if info.eventAccess %}
                                <div class="tools">
                                    <i class="fa fa-trash-o js-delete" data-url="/ajax/calendar/delete_event" data-type="ajax"></i>
                                </div>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div><!-- /.box-body -->

        </div>
    </div>
</div>